<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos [
    <!ELEMENT alumnos (alumno*)>
    <!ELEMENT alumno (nombre, nacimiento, apellido, curso)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT nacimiento (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT curso (#PCDATA)>
    <!ATTLIST alumno
        id ID #REQUIRED
        edad CDATA #IMPLIED
        becado (si | no) "no">
]>
<alumnos>
    <alumno id="a1" edad="20" becado="si">
        <nombre>Eren</nombre>
        <nacimiento>30/marzo/835</nacimiento>
        <apellido>Jaeger</apellido>
        <curso>Mates</curso>
    </alumno>
    <alumno id="a20" becado="no">
        <nombre>Mikasa</nombre>
        <nacimiento>10/febrero/2005</nacimiento>
        <apellido>Ackerman</apellido>
        <curso>Español</curso>
    </alumno>
    <alumno id="a2" edad="29">
        <nombre>Pedro</nombre>
        <nacimiento>02/julio/1995</nacimiento>
        <apellido>Juárez</apellido>
        <curso>Ciencias</curso>
    </alumno>
</alumnos>
